### ISSUE TITLE
GitHubTeacher work on the GitHub Flow

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/basel-october-everyone#7]
### TODOs for GitHub Flow
- [x] Look at the [GitHub Flow](https://guides.github.com/introduction/flow/)
- [x] Open an issue
- [x] Add "code" by creating a branch
- [x] Open a PR
- [x] Add commits
- [x] Get peer review
- [x] Merge PR
